components:
  - files:
      - bin/git-rev-max-wc-lines
    implemented-in:
      - sh
    depends:
      debian-apt:
        - git
        - perl
        - parallel
        - awk
        - coreutils
